<?php

namespace Database\Seeders;

use App\Models\ChecklistItem;
use Illuminate\Database\Seeder;
use App\Models\ChecklistSubCategory;

class ChecklistItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $checklist_items = [
            ['name' => "Fire Extinguisher", 'notes' => null],
            ['name' => "Spare Wheel", 'notes' => null ],
            ['name' => "Triangles", 'notes' => null ],
            
            ['name' => "Driver License", 'notes'  => 'Within re-test period'],
            ['name' => "Defense Driving Certificate" , 'notes'  => 'Within re-test period'],
            ['name' => "Medical Certificate" , 'notes'  => 'Within re-test period'],
            ['name' => "Hazchem" , 'notes'  => 'Within re-test period'],
            ['name' => "Driver PPE (helmet, shoes, anti-static clothes, gloves, gogles)" , 'notes'  => 'All correct PPE Required' ],
            ['name' => "Is driver on medication", 'notes'  => 'No Driving Under the influence of D & A' ],
            ['name' => "Is mobile phone switched off", 'notes' => null ],
            //truck accreditation
            ['name' => "Truck License", 'notes' => 'Within re-test period' ],
            ['name' => "Truck Certificate of Fitness", 'notes' => 'Within re-test period' ],
            ['name' => "Valid calibration chart", 'notes' => 'Correct reference height' ],
            ['name' => "Self Starting", 'notes' => 'Vehicle must be able to self start' ],
            ['name' => "Safety Belts", 'notes' => 'In good condition-3 fixing points-driver and passenger side' ],
            ['name' => "Fire Extinguisher - 1x2kg for the cabin", 'notes' => 'Dry powder - validity date-sealed + pressure gauge on green' ],
            ['name' => "Correct flame arrestor (exhaust system)", 'notes' => 'Heat Shield Required' ],
            ['name' => "Brakes", 'notes' => 'Vehicle must have efficient brakes' ],
            ['name' => "Parking Brake (hand brake)", 'notes' => 'Has to be working' ],
            ['name' => "Lights (front, rear, indicators, stop, headlights, no naked bulbs)", 'notes' => 'Must be operational - all protecting covered in good condition' ],
            ['name' => "Visibility (side mirrors, windows, windscreen, wipers free of blemishes & cracks)", 'notes' => 'Refuse in case of flagrant (spider web) lack of visibility' ],
            ['name' => "Battery isolation / master switch", 'notes' => 'Labelled installed and working' ],
            ['name' => "Battery cover", 'notes' => 'Properly insulated / or be of non conductive material' ],
            ['name' => "Tyres(rolling)", 'notes' => 'Treads visible over the complete tread area (minimum groove 2.5mm) ' ],
            ['name' => "Wheels / rims including spare wheel(s) no cracks and full complement of nuts", 'notes' => null ],
            ['name' => "Spare wheel(s)", 'notes' => 'Treads visible over the complete tread area (minimum groove 2.5mm) ' ],
            ['name' => "Hazardous product sign (1203 or 3ye stickers)", 'notes' => 'On each side and one at the back with Zim contact numbers' ],
            ['name' => "Bonding Cable + Earthing Stud / pin", 'notes' => 'Free from rust and not painted' ],
            ['name' => "Compartment capacities for each product", 'notes' => 'Capacity of each compartment must be marked to prevent over filling, spills and over loading' ],
            ['name' => "Maximum volume(s) of the tank product", 'notes' => null ],
            ['name' => "Drip tray under valves", 'notes' => 'Must have working drain valve' ],
            ['name' => "Horse condition", 'notes' => 'Rubber seals intact and no cracks' ],
            ['name' => "Correct foot valves + Emergency shutt off switch", 'notes' => null ],
            ['name' => "Fire Extinguisher - 2 x 9 kg for the trailer", 'notes' => 'Dry powder - validity date - sealed + pressure gauge on green' ],
            ['name' => "Ladder, upper gangway : guard rail", 'notes' => 'in good condition - well fixed - non slip upper part' ],
            ['name' => "Compartment cleanliness", 'notes' => null ],
            ['name' => "Manhole seals (dome covers)", 'notes' => 'seals must be intact to prevent intransit leaks and loses' ],
            ['name' => "Tank valves, pipes, caps", 'notes' => 'stop loading & offload if there are leaks prior and during loading' ],
            ['name' => "Other known defects", 'notes' => null ],
            ['name' => "Electrical Wiring & Fittings" , 'notes' => null],
            ['name' => "Exhaust System", 'notes' => null ],
            ['name' => "Handrail", 'notes' => null ],
            ['name' => "Wheel Chocks" , 'notes' => null],
            ['name' => "Air Leaks", 'notes' => null ],

                    // intermediate inspection of the trailer / tanker
            
                    ['name' => "U Bolts", 'notes' => null ],
                    ['name' => "Equalizer Hanger", 'notes' => null ],
                    ['name' => "Engualiser bushes", 'notes' => null ],
                    ['name' => "Torque Arm", 'notes' => null ],
                    ['name' => "Torque Arm Bushes", 'notes' => null ],
                    ['name' => "Scam Bushes", 'notes' => null ],
                    ['name' => "Slack Adjusters", 'notes' => null ],
                    ['name' => "Air Leaks", 'notes' => null ],
                    ['name' => "Springs", 'notes' => null ],
                    ['name' => "Brake Chamber", 'notes' => null ],
                    ['name' => "Brake Drum", 'notes' => null ],
                    ['name' => "Brake Linings", 'notes' => null ],
                    ['name' => "Cracks", 'notes' => null ],
                    ['name' => "RIMS", 'notes' => null ],
                    ['name' => "STUDS", 'notes' => null ],
                    ['name' => "Wheel Nuts", 'notes' => null ],
                    ['name' => "Adjust Breaks", 'notes' => null ],
                    ['name' => "Landing Gears", 'notes' => null ],
                    ['name' => "Load Fasteners", 'notes' => null ],
                    ['name' => "Tool Box", 'notes' => null ],
                    ['name' => "Spare Wheel Carriage", 'notes' => null ],
                    ['name' => "Spare Wheel", 'notes' => null ],
                    ['name' => "Lubricate all nipples", 'notes' => null ],
                    ['name' => "Air & Electric Connections", 'notes' => null ],
                    ['name' => "T. Sign", 'notes' => null ],
                    ['name' => "Stop Lights", 'notes' => null ],
                    ['name' => "Indicators", 'notes' => null ],
                    ['name' => "Number Plate Light", 'notes' => null ],
                    ['name' => "Chevron", 'notes' => null ],
                    ['name' => "Fire Extinguisher", 'notes' => null ],
                    ['name' => "Fire Extinguisher holder", 'notes' => null ],
                    ['name' => "Tarpaulin", 'notes' => null ],
                    ['name' => "King Pin", 'notes' => null ],
                    ['name' => "Hub Caps", 'notes' => null ],
                    ['name' => "Speed Limit Stickers 60 - 70 - 80 - (90) ", 'notes' => null ],
                    ['name' => "Reflective plates - Triangles - reflectors", 'notes' => null ],
                    ['name' => "Hazard - Flames - Environment placards", 'notes' => null ],
                    ['name' => "License Plate", 'notes' => null ],
                    ['name' => "Junction boxes", 'notes' => null ],
                    ['name' => "Drip Valves", 'notes' => null ],
                    ['name' => "Tank Tightness", 'notes' => null ],
                    ['name' => "Verify Bottom check valves", 'notes' => null ],
                    ['name' => "Check the ladder - guardrail - mid rail", 'notes' => null ],
                    ['name' => "Check recovery horses Vapors - Dipstick" , 'notes' => null],
                    ['name' => "Check landing gear - Lubrication", 'notes' => null ],
                    ['name' => "Underrun protection bars - Fender flares - Mud flaps", 'notes' => null ],
         
                    // intermediate inspection of the truck
        
                    ['name' => "Engine Oil Level & Viscosity", 'notes' => null ],
                    ['name' => "Coolant Level and Air Cleaner", 'notes' => null ],
                    ['name' => "Engine Sound", 'notes' => null ],
                    ['name' => "Drive belts", 'notes' => null ],
                    ['name' => "Fan & Fan Hub condition", 'notes' => null ],
                    ['name' => "Engine Mountings" , 'notes' => null],
                    ['name' => "Dashboard Controls", 'notes' => null ],
                    ['name' => "Engine Leaks", 'notes' => null ],
                    ['name' => "Front Hubs Bearing Pre-Load", 'notes' => null ],
                    ['name' => "Kingpins", 'notes' => null ],
                    ['name' => "Power steering system", 'notes' => null ],
                    ['name' => "The DC D end and drag link drop arm", 'notes' => null ],
                    ['name' => "Starter motor crank speed and condition", 'notes' => null ],
                    ['name' => "Alternator condition and charge rate", 'notes' => null ],
                    ['name' => "Gear box differential oil level", 'notes' => null ],
                    ['name' => "Up & Down Clutch Free Play Gaps", 'notes' => null ],
                    ['name' => "Air 8 GS positioning and levelling", 'notes' => null ],
                    ['name' => "Bolts and springs hanger bolts", 'notes' => null ],
                    ['name' => "Drain Air Tanks", 'notes' => null ],
                    ['name' => "Batteries Condition and cut off switch", 'notes' => null ],
                    ['name' => "Brake boosters and actuating angles", 'notes' => null ],
                    ['name' => "Brakes unings and brake drums", 'notes' => null ],
                    ['name' => "Brakes adjustment", 'notes' => null ],
                    ['name' => "Air leaks" , 'notes' => null],
                    ['name' => "Water leaks" , 'notes' => null],
                    ['name' => "Compressor Efficiency", 'notes' => null ],
                    ['name' => "Bell housing bolts", 'notes' => null ],
                    ['name' => "Propeller shaft universal joints and flange nuts", 'notes' => null ],
                    ['name' => "Center bearing and wheel nuts" , 'notes' => null],
                    ['name' => "Rear and front diffs axle hub pre load and seals", 'notes' => null ],
                    ['name' => "Slack Adjusters and S Cams", 'notes' => null ],
                    ['name' => "Through shaft seal", 'notes' => null ],
                    ['name' => "Rear gearbox seal", 'notes' => null ],
                    ['name' => "Accessory drive seal", 'notes' => null ],
                    ['name' => "Rean and front crankshaft seal", 'notes' => null ],
                    ['name' => "Fifth wheel jaws and bushes", 'notes' => null ],
                    ['name' => "Air Dryer and  D2 Valve", 'notes' => null ],
                    ['name' => "E.C.N and electrical looms and wiring", 'notes' => null ],
                    ['name' => "Ignition", 'notes' => null ],
                    ['name' => "Diesel filter and fuel water seperator", 'notes' => null ],
                    ['name' => "Gearbox high and low split pipes" , 'notes' => null],
                    ['name' => "Tail and lead lights", 'notes' => null ],
                    ['name' => "Fender seat belts and doors", 'notes' => null ],
                    ['name' => "Wipers and wiper mortar", 'notes' => null ],
                    ['name' => "Car airbags", 'notes' => null ],
                    ['name' => "Diffs and steering axle shock absorbers", 'notes' => null ],
                    ['name' => "Springs tension and bushes hangers", 'notes' => null ],
                    ['name' => "Brake pedal free play", 'notes' => null ],
                    ['name' => "Trailer brake valve" , 'notes' => null],
                    ['name' => "Hand brake valve" , 'notes' => null],
                    ['name' => "Foot brake valve" , 'notes' => null],
                    ['name' => "Height lights and hooter", 'notes' => null ],
                    ['name' => "Chasis cracks and cross members" , 'notes' => null],
                    ['name' => "Exhaust Manifold, Exhaust Line and Turbo", 'notes' => null ],
                    ['name' => "Water pump, oil pump and oil cooler", 'notes' => null ],
                    ['name' => "Sump bolts and cam boxes", 'notes' => null ],
                    ['name' => "Thermostat housing", 'notes' => null ],
                    ['name' => "Timing cover gasket" , 'notes' => null],
                    ['name' => "Greasing", 'notes' => null ],
                    ['name' => "Radiator and Header tank" , 'notes' => null],
                    ['name' => "Intercooler and inlet manifold", 'notes' => null ],
                    ['name' => "Diesel cross-over pipes and jumper tube", 'notes' => null ],
                    ['name' => "Chevron 5 core cable and suzzy pipes", 'notes' => null ],
                    ['name' => "Stabilizer bar bushes", 'notes' => null ],
                    ['name' => "View mirrors and grill", 'notes' => null ],
                    ['name' => "Steering and bump stoppers", 'notes' => null ],
                    ['name' => "Steering wheel freeplay", 'notes' => null ],
                    ['name' => "Bonnet bushes and seats", 'notes' => null ],
                    ['name' => "ABS lights (TRR and SREM)", 'notes' => null ],
                    ['name' => "Emergency Hammer - Seatbelt Cutter", 'notes' => null ],
                    ['name' => "Wheel Choc + 2 Trialngles", 'notes' => null ],
                    ['name' => "Speed Limit Stickers - 60 - 70 - 80 -(90)", 'notes' => null ],
                    ['name' => "Hazard placards - supports", 'notes' => null ],
                    ['name' => "License plates", 'notes' => null ],
                    ['name' => "Tyre condition - pressure - overheating / tigtening light", 'notes' => null ],
                    ['name' => "Maintenance Log Update - Label", 'notes' => null ],

        ];
        ChecklistItem::insert($checklist_items);
        
    }
}
